# Generated by Django 3.2.9 on 2021-11-09 07:12

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('user_DOB', models.DateField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('task_category', models.CharField(choices=[('Home Task', 'Home Task'), ('Office Task', 'Office Task'), ('Miscellenious Task', 'Mescillineous')], max_length=20)),
                ('task_start_date', models.DateTimeField(default=datetime.datetime(2021, 11, 9, 7, 12, 21, 757088))),
                ('task_end_date', models.DateTimeField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoApp.person')),
            ],
        ),
    ]
