# Generated by Django 3.2.9 on 2021-11-09 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 9, 42, 9, 478258)),
        ),
    ]
