# Generated by Django 3.2.9 on 2021-11-09 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_auto_20211109_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 11, 9, 25, 90795)),
        ),
    ]
